# Generated by Django 2.2.1 on 2019-05-19 00:46

import core.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                (
                    'id',
                    core.fields.CharField(
                        help_text='Telegram chat ID.',
                        primary_key=True,
                        serialize=False,
                        unique=True
                    )
                ),
                (
                    'buttons',
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100), default=list, size=None
                    )
                ),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                (
                    'id',
                    core.fields.CharField(
                        help_text='Telegram message ID merged with chat ID.',
                        primary_key=True,
                        serialize=False,
                        unique=True
                    )
                ),
                (
                    'chat',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Chat')
                ),
            ],
        ),
        migrations.CreateModel(
            name='Button',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    )
                ),
                ('index', models.IntegerField()),
                ('text', core.fields.CharField(max_length=100)),
                ('count', models.IntegerField(default=0)),
                ('permanent', models.BooleanField(default=False)),
                (
                    'message',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='core.Message'
                    )
                ),
            ],
            options={
                'ordering': ('index',),
                'unique_together': {('message', 'text')},
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    )
                ),
                ('user_id', core.fields.CharField(help_text='Telegram user ID.')),
                (
                    'button',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='core.Button'
                    )
                ),
                (
                    'message',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='core.Message'
                    )
                ),
            ],
            options={
                'unique_together': {('user_id', 'message')},
            },
        ),
    ]
