# Generated by Django 2.2.1 on 2019-05-09 13:02

import core.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_id', core.fields.CharField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keyboard',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    )
                ),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                (
                    'message_id',
                    core.fields.CharField(primary_key=True, serialize=False, unique=True)
                ),
                (
                    'chat',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Chat')
                ),
                (
                    'keyboard',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='core.Keyboard'
                    )
                ),
            ],
            options={
                'unique_together': {('chat', 'message_id')},
            },
        ),
        migrations.AddField(
            model_name='chat',
            name='keyboard',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to='core.Keyboard'
            ),
        ),
        migrations.CreateModel(
            name='Button',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    )
                ),
                ('index', models.IntegerField()),
                ('text', core.fields.CharField(max_length=100)),
                (
                    'keyboard',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='core.Keyboard'
                    )
                ),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    )
                ),
                ('user_id', core.fields.CharField()),
                (
                    'button',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='core.Button'
                    )
                ),
                (
                    'message',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='core.Message'
                    )
                ),
            ],
            options={
                'unique_together': {('user_id', 'message')},
            },
        ),
    ]
