# Generated by Django 2.2.1 on 2019-05-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='is_chat',
            field=models.BooleanField(default=False),
        ),
    ]
