# Generated by Django 2.2.1 on 2019-05-21 12:25

import core.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='inline_message_id',
            field=core.fields.CharField(
                blank=True, help_text='Telegram ID of inline message.', null=True
            ),
        ),
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Chat'
            ),
        ),
        migrations.AlterField(
            model_name='message',
            name='original_message_id',
            field=core.fields.CharField(
                blank=True,
                help_text='Telegram ID of original message w/o appended chat ID.',
                null=True
            ),
        ),
    ]
