# Generated by Django 2.2.1 on 2019-05-23 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190521_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='allow_reactions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='force_emojis',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chat',
            name='add_padding',
            field=models.BooleanField(default=False),
        ),
    ]
