# Generated by Django 2.2.1 on 2019-05-23 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190523_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='repost',
            field=models.BooleanField(default=True),
        ),
    ]
