# Generated by Django 2.2.1 on 2019-05-24 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_chat_repost'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
