# Generated by Django 2.2.1 on 2019-05-24 23:30

import core.fields
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_message_anonymous'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserButtons',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    )
                ),
                (
                    'buttons',
                    django.contrib.postgres.fields.ArrayField(
                        base_field=core.fields.CharField(), size=None
                    )
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                (
                    'user',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User')
                ),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='MessageToPublish',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    )
                ),
                ('message', django.contrib.postgres.fields.jsonb.JSONField()),
                (
                    'buttons',
                    django.contrib.postgres.fields.ArrayField(
                        base_field=core.fields.CharField(), blank=True, null=True, size=None
                    )
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                (
                    'user',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User')
                ),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
