# Generated by Django 2.2.3 on 2019-08-02 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_messagetopublish_userbuttons'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularReactions',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    )
                ),
                ('updated', models.DateTimeField()),
                (
                    'chat',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to='core.Chat'
                    )
                ),
            ],
            options={
                'verbose_name': 'Popular Reactions',
                'verbose_name_plural': 'Popular Reactions',
            },
        ),
        migrations.CreateModel(
            name='TopPosters',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    )
                ),
                ('updated', models.DateTimeField()),
                (
                    'chat',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to='core.Chat'
                    )
                ),
            ],
            options={
                'verbose_name': 'Top Posters',
                'verbose_name_plural': 'Top Posters',
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    )
                ),
                ('text', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
                (
                    'root',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='items',
                        to='stats.PopularReactions'
                    )
                ),
            ],
            options={
                'ordering': ('-count',),
            },
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    )
                ),
                ('messages', models.IntegerField(help_text='Number of messages posted by user.')),
                (
                    'reactions',
                    models.IntegerField(help_text="Number of reactions on user's posts.")
                ),
                (
                    'root',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='items',
                        to='stats.TopPosters'
                    )
                ),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to='core.User'
                    )
                ),
            ],
            options={
                'ordering': ('-reactions', '-messages'),
            },
        ),
    ]
