# Generated by Django 2.2.3 on 2019-08-01 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_messagetopublish_userbuttons'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularReactions',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    )
                ),
                ('updated', models.DateTimeField()),
                (
                    'chat',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Chat')
                ),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    )
                ),
                ('text', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
                (
                    'root',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='stats.PopularReactions'
                    )
                ),
            ],
            options={
                'ordering': ('-count',),
            },
        ),
    ]
